### ISSUE TITLE
Fail to build pngquant with cargo in windows

### ISSUE THREAD

**Issue by ZanderChang** [kornelski/pngquant#327]
I tried to compile pngquant in windows but it failed. After `cargo build --release`,  it shows :
```
PS D:\Codes\pngquant-2.12.2> cargo build --release
   Compiling arrayvec v0.4.10
   Compiling libc v0.2.50
   Compiling cfg-if v0.1.7
   Compiling nodrop v0.1.13
   Compiling memoffset v0.2.1
   Compiling lazy_static v1.3.0
   Compiling scopeguard v0.3.3
   Compiling rayon-core v1.4.1
   Compiling rayon v1.0.3
   Compiling either v1.5.1
   Compiling pkg-config v0.3.14
   Compiling vcpkg v0.2.6
   Compiling dunce v0.1.1
   Compiling rgb v0.8.13
   Compiling unicode-width v0.1.5
   Compiling glob v0.2.11
   Compiling crossbeam-utils v0.2.2
   Compiling getopts v0.2.18
   Compiling wild v2.0.1
   Compiling num_cpus v1.10.0
   Compiling crossbeam-epoch v0.3.1
   Compiling crossbeam-deque v0.2.0
   Compiling cc v1.0.32
   Compiling libz-sys v1.0.25
   Compiling lcms2-sys v2.4.8
   Compiling libpng-sys v1.1.2
   Compiling imagequant-sys v2.12.2 (D:\Codes\pngquant-2.12.2\lib)
   Compiling pngquant v2.12.2 (D:\Codes\pngquant-2.12.2)
error: failed to run custom build command for `pngquant v2.12.2 (D:\Codes\pngquant-2.12.2)`
process didn't exit successfully: `D:\Codes\pngquant-2.12.2\target\release\build\pngquant-053a8db83b6fc68a\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "C:\\Users\\zhang\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\lcms2-sys-2.4.8\\vendor\\include" "/I" "D:\\Codes\\pngquant-2.12.2\\lib\\msvc-dist" "/DPNGQUANT_NO_MAIN=1" "/DUSE_LCMS=1" "/DNDEBUG=1" "/DUSE_SSE=1" "/FoD:\\Codes\\pngquant-2.12.2\\target\\release\\build\\pngquant-93d54afbafef1f07\\out\\rwpng.o" "/c" "rwpng.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\zhang\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.32\src\lib.rs:2367:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:340
   9: cc::Tool::to_command
  10: cc::Build::compile
  11: core::ptr::real_drop_in_place
  12: <alloc::raw_vec::RawVec<T, A>>::reserve
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure,i32>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:297
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libpanic_unwind\lib.rs:92
  16: std::panicking::try
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:276
  17: std::panic::catch_unwind
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panic.rs:388
  18: std::rt::lang_start_internal
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:48
  19: main
  20: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  21: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

The main environment is  `Windows10 x64, vs2017, cargo 1.33.0, rustup 1.17.0, rustc 1.33.0`.

Could anybody help fix this ? Thanks a lot.

**Comment by ZanderChang** [comment]
When I tested with `Windows7 x64` and `vs2015`, it showed that `rwpng.c` can't find `png.h`

**Comment by kornelski** [comment]
I'll check that.

**Comment by ZanderChang** [comment]
Well, I reconstructed the project directly with `vs2017` and finally it worked. I think `rust` is hard to use and understand.

**Comment by kornelski** [comment]
Well, the Rust part worked. The error is from the C compiler.
